### ISSUE TITLE
follow readme

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro-regtest#1]
Hi, I'm following the readme, but the `start.sh` file doesn't exist.

> Add this ENV variables to your .env file (assuming that the mostro-regtest directory is in ../ from the mostro directory)

The `.env` you are referring to is the one inside the `Mostro` directory?

Should i do `docker compose up` or something else?

Thanks! Sorry my noobs questions 😅

**Comment by ifuensan** [comment]
Hi Catrya!

I started this project in the B4OS residency but couldn't complete it. I'll let you know when it's ready for you to test.

¡Gracias por preguntar!

**Comment by ifuensan** [comment]
Hi @Catrya!

@z017 has made many changes in the repo. Could you test it and let us know how it works?

I’m closing this issue for now, but we’ll open new ones if needed.

Thanks!
